- type: job
  id: BoSWashingtonInitiate
  setPreference: true
  name: job-name-bos-washington-initiate
  description: job-description-bos-washington-initiate
  playTimeTracker: BoSWashingtonInitiate
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterOverallTimeRequirement
      min: 3600
  startingGear: BoSWashingtonInitiateGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-wash-initiate
  canBeAntag: false
  access:
  - WashingtonInitiate
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWashington

- type: startingGear
  id: BoSWashingtonInitiateGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatFilled
    id: N14IDBrotherhoodWashingtonHolotagInitiate
    head: N14ClothingHeadHatBrotherhoodHelmet # Corvax-N14
    outerClothing: N14ClothingOuterCombatArmorBOS
    belt: ClothingBeltBoSWebbing
    pocket1: BoSWashingtonStandartKits # Corvax-N14

- type: playTimeTracker
  id: BoSWashingtonInitiate
