- type: job
  id: Overseer
  name: job-name-overseer
  description: job-description-overseer
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterDepartmentTimeRequirement
    department: Vault
    min: 36000 # 10 hours
  playTimeTracker: Overseer
  weight: 20
  startingGear: OverseerGear
  alwaysUseSpawner: true
  icon: "JobIconVaultOverseer" # Forge-Change
  requireAdminNotify: true
  joinNotifyCrew: true
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  supervisors: job-supervisors-vault-overseer
  accessGroups:
  - VaultOverseer
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Vault

- type: startingGear
  id: OverseerGear
  subGear: # Forge-Change
  - OverseerGearSponsor
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultBlue # Forge-Change
    shoes: N14ClothingBootsBlack
    eyes: ClothingEyesGlassesSunglasses
    id: N14VaultOverseerPDA
    ears: N14ClothingHeadsetVaultDweller
    pocket1: N14WeaponPistol10mm
  innerClothingSkirt: N14ClothingUniformJumpsuitVault14
  storage: # Forge-Change
    back:
    - N14Bandage
    - N14CurrencyPrewarMoney500
    - N14CurrencyPrewarMoney500

- type: startingGear # Forge-Change
  id: OverseerGearSponsor
  requirements:
  - !type:SponsorRequirement
    level: 2
  equipment:
    id: N14VaultOverseerPDAGold

- type: playTimeTracker
  id: Overseer
